name: flutter_shopping
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  auto_route: ^7.9.2
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^4.8.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
  json_serializable: ^6.8.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/yekan_light.ttf
          weight: 300
        - asset: assets/fonts/yekan.ttf
          weight: 400
        - asset: assets/fonts/yekan_medium.ttf
          weight: 500
        - asset: assets/fonts/yekan_bold.ttf
          weight: 700
        - asset: assets/fonts/yekan_extra_bold.ttf
          weight: 800

  assets:
    - assets/icons/

